apiVersion: v1
kind: Service
metadata:
  name: authservice-service
  labels:
    app: authservice
spec:
  selector:
    app: authservice
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32434
    name: app
  type: NodePort
