apiVersion: v1
kind: Service
metadata:
  name: authservice-service-staging
  namespace: staging
  labels:
    app: authservice
    env: staging
spec:
  selector:
    app: authservice
    env: staging
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30002
  type: NodePort
