apiVersion: v1
kind: Service
metadata:
  name: authservice-service-testing
  labels:
    app: authservice
    env: testing
spec:
  selector:
    app: authservice
    env: testing
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30001
  type: NodePort
